version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
    - "3000:80"
    volumes:
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
#    ports:
#    - "3000:3000"
    environment:
    - PORT=3000
    depends_on:
      - mongo
#    env_file:
#      - ./.env

  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=app
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis:5-alpine

volumes:
  mongo-db: